/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package startup;

/**
 *
 * @author rajea
 */
public class MaterialBackground extends javax.swing.JPanel {

    /**
     * Creates new form MaterialBackground
     */
    java.net.URL backgroundImageURL;
    java.awt.image.BufferedImage backgroundImage;
    public MaterialBackground() {
        initComponents();
        try
        {
        backgroundImageURL = this.getClass().getResource("BACK.PNG");
        backgroundImage = javax.imageio.ImageIO.read(backgroundImageURL);
        }
        catch(java.io.IOException e)
        {
            System.out.println("IO Exception."+e);
        }
        super.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    public void paintComponent(java.awt.Graphics drawIt)
    {
        super.paintComponent(drawIt);
        java.awt.Graphics2D jarvisGraphics2d = (java.awt.Graphics2D)drawIt;
        java.awt.RenderingHints renderHints = new java.awt.RenderingHints(java.awt.RenderingHints.KEY_ANTIALIASING,java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        renderHints.put(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);
        jarvisGraphics2d.addRenderingHints(renderHints);
        jarvisGraphics2d.drawImage(backgroundImage, 0, 0, getWidth(),getHeight(),this);
        repaint();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
