/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processor;

/**
 *
 * @author rajea
 */
public class CompletedProcess extends javax.swing.JPanel {

    /**
     * Creates new form CompletedProcess
     */
    public CompletedProcess(String processName,int processProfit, int processTime, int Serial,String processArrival, String processEndExecution) {
        initComponents();
        CPL_PNAME.setText(processName);
        CPL_PPROFIT.setText(""+processProfit);
        CPL_PTIME.setText(""+processTime);
        CPL_SR.setText(""+Serial);
        CPL_PROCESS_ARRIVAL.setText(processArrival);
        //CPL_PROCESS_CPU_IN.setText(processStartExecution);
        CPL_PROCESS_CPU_OUT.setText(processEndExecution);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CPL_PNAME = new javax.swing.JLabel();
        CPL_SR = new javax.swing.JLabel();
        CPL_PPROFIT = new javax.swing.JLabel();
        CPL_PTIME = new javax.swing.JLabel();
        CPL_PROCESS_ARRIVAL = new javax.swing.JLabel();
        CPL_PROCESS_CPU_OUT = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0,0,0,0));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 51, 0)));
        setMaximumSize(new java.awt.Dimension(950, 70));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 80));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        CPL_PNAME.setBackground(new java.awt.Color(0,0,0,0));
        CPL_PNAME.setFont(new java.awt.Font("Caviar Dreams", 1, 36)); // NOI18N
        CPL_PNAME.setForeground(new java.awt.Color(255, 51, 0));

        CPL_SR.setBackground(new java.awt.Color(0,0,0,0));
        CPL_SR.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        CPL_SR.setForeground(new java.awt.Color(255, 51, 0));
        CPL_SR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CPL_SR.setText("1");

        CPL_PPROFIT.setBackground(new java.awt.Color(0,0,0,0));
        CPL_PPROFIT.setFont(new java.awt.Font("Caviar Dreams", 0, 24)); // NOI18N
        CPL_PPROFIT.setForeground(new java.awt.Color(255, 51, 0));
        CPL_PPROFIT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        CPL_PTIME.setBackground(new java.awt.Color(0,0,0,0));
        CPL_PTIME.setFont(new java.awt.Font("Caviar Dreams", 0, 24)); // NOI18N
        CPL_PTIME.setForeground(new java.awt.Color(255, 51, 0));
        CPL_PTIME.setText("25");
        CPL_PTIME.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        CPL_PROCESS_ARRIVAL.setBackground(new java.awt.Color(0,0,0,0));
        CPL_PROCESS_ARRIVAL.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        CPL_PROCESS_ARRIVAL.setForeground(new java.awt.Color(255, 51, 0));
        CPL_PROCESS_ARRIVAL.setText("10:20:50 AM");
        CPL_PROCESS_ARRIVAL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Process Arrival Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        CPL_PROCESS_CPU_OUT.setBackground(new java.awt.Color(0,0,0,0));
        CPL_PROCESS_CPU_OUT.setFont(new java.awt.Font("Caviar Dreams", 1, 24)); // NOI18N
        CPL_PROCESS_CPU_OUT.setForeground(new java.awt.Color(255, 51, 0));
        CPL_PROCESS_CPU_OUT.setText("10:20:50 AM");
        CPL_PROCESS_CPU_OUT.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Process Completion Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 51, 0))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(CPL_SR, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPL_PNAME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(CPL_PPROFIT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPL_PTIME, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPL_PROCESS_ARRIVAL, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPL_PROCESS_CPU_OUT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPL_PPROFIT, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPL_PNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPL_SR)
                    .addComponent(CPL_PTIME)
                    .addComponent(CPL_PROCESS_ARRIVAL)
                    .addComponent(CPL_PROCESS_CPU_OUT)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
       this.setBackground(new java.awt.Color(51,0,0,125));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(new java.awt.Color(0,0,0,0));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPL_PNAME;
    private javax.swing.JLabel CPL_PPROFIT;
    private javax.swing.JLabel CPL_PROCESS_ARRIVAL;
    private javax.swing.JLabel CPL_PROCESS_CPU_OUT;
    private javax.swing.JLabel CPL_PTIME;
    private javax.swing.JLabel CPL_SR;
    // End of variables declaration//GEN-END:variables
}
