/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processor;

/**
 *
 * @author Raje Abhilash Mohite
 */
public class Process extends javax.swing.JPanel{

    /**
     * Creates new form PEMProcessStack
     * @param Name This is used to Display Name of Process
     * @param Profit
     * @param Time
     * @param getIndex
     */
        public String processName;
        int processProfit,processTime;
        int Index;
        String Time_Execute,Time_Execute_After;
        String ArrivalTime;
        String Completing_on;
        promula_util.TimeManager timer;
        
    public Process(String Name,int Profit, int Time,int getIndex) {
        initComponents();
        processName = Name;
        processProfit = Profit;
        processTime = Time;       
        timer = new promula_util.TimeManager();
        ArrivalTime = new java.text.SimpleDateFormat("hh:mm:ss a").format(new java.util.Date(System.currentTimeMillis()));
        Completing_on = timer.addTime(ArrivalTime, processTime);
        PSR.setText(""+getIndex);
        PName.setText(Name);
        PPoints.setText(Profit+" Points.");
        PTime.setText(""+Time);
        PArrival.setText(ArrivalTime);
    }
    public void updateTimeToExecute(String getTimeToExecute)
    {
        Time_Execute = getTimeToExecute;
        PTIME_TO_EXECUTE.setText(Time_Execute);
    }
    public void updateTimeOfCompletion(String getTimeToComplete)
    {
        Completing_on = getTimeToComplete;
        PTIME_TO_EXECUTE_AFTER.setText(Completing_on);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PName = new javax.swing.JLabel();
        PPoints = new javax.swing.JLabel();
        PTime = new javax.swing.JLabel();
        PL_PROFIT = new javax.swing.JLabel();
        PL_ARRIVAL = new javax.swing.JLabel();
        PL_TTE = new javax.swing.JLabel();
        PArrival = new javax.swing.JLabel();
        PSR = new javax.swing.JLabel();
        PL_CEA = new javax.swing.JLabel();
        PTIME_TO_EXECUTE = new javax.swing.JLabel();
        PTIME_TO_EXECUTE_AFTER = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255,0,204,10));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 0, 255)));
        setMaximumSize(new java.awt.Dimension(400, 182));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        PName.setBackground(new java.awt.Color(102, 0, 102));
        PName.setFont(new java.awt.Font("EA Font v1.5 by Ghettoshark", 0, 36)); // NOI18N
        PName.setForeground(new java.awt.Color(255, 51, 255));
        PName.setText("PROCESS NAME");
        PName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 255)));

        PPoints.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        PPoints.setForeground(new java.awt.Color(255, 51, 255));
        PPoints.setText("500 Points.");

        PTime.setFont(new java.awt.Font("EA Font v1.5 by Ghettoshark", 0, 60)); // NOI18N
        PTime.setForeground(new java.awt.Color(255, 51, 255));
        PTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PTime.setText("50");

        PL_PROFIT.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        PL_PROFIT.setForeground(new java.awt.Color(255, 51, 255));
        PL_PROFIT.setText("Profit :");

        PL_ARRIVAL.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        PL_ARRIVAL.setForeground(new java.awt.Color(255, 51, 255));
        PL_ARRIVAL.setText("Arrival :");

        PL_TTE.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        PL_TTE.setForeground(new java.awt.Color(255, 51, 255));
        PL_TTE.setText("Time to Execute :");

        PArrival.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        PArrival.setForeground(new java.awt.Color(255, 51, 255));
        PArrival.setText("00:00:00 AM");

        PSR.setBackground(new java.awt.Color(102, 0, 102));
        PSR.setFont(new java.awt.Font("EA Font v1.5 by Ghettoshark", 0, 36)); // NOI18N
        PSR.setForeground(new java.awt.Color(255, 51, 255));
        PSR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PSR.setText("01 ");
        PSR.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 255)));

        PL_CEA.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        PL_CEA.setForeground(new java.awt.Color(255, 51, 255));
        PL_CEA.setText("Complete Execution After :");

        PTIME_TO_EXECUTE.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        PTIME_TO_EXECUTE.setForeground(new java.awt.Color(255, 51, 255));
        PTIME_TO_EXECUTE.setText("00:00:00 AM");

        PTIME_TO_EXECUTE_AFTER.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        PTIME_TO_EXECUTE_AFTER.setForeground(new java.awt.Color(255, 51, 255));
        PTIME_TO_EXECUTE_AFTER.setText("00:00:00 AM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PL_TTE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PTIME_TO_EXECUTE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PL_ARRIVAL)
                                        .addGap(6, 6, 6)
                                        .addComponent(PArrival))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PL_PROFIT)
                                        .addGap(12, 12, 12)
                                        .addComponent(PPoints)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PTime, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(PL_CEA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PTIME_TO_EXECUTE_AFTER)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PSR, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(PName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PName)
                    .addComponent(PSR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PL_PROFIT)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(PPoints)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PL_ARRIVAL)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(PArrival)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PL_TTE)
                            .addComponent(PTIME_TO_EXECUTE)))
                    .addComponent(PTime, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PL_CEA)
                    .addComponent(PTIME_TO_EXECUTE_AFTER))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new java.awt.Color(62,7,63,200));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
       setBackground(new java.awt.Color(255,0,204,10));
    }//GEN-LAST:event_formMouseExited

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PArrival;
    private javax.swing.JLabel PL_ARRIVAL;
    private javax.swing.JLabel PL_CEA;
    private javax.swing.JLabel PL_PROFIT;
    private javax.swing.JLabel PL_TTE;
    private javax.swing.JLabel PName;
    private javax.swing.JLabel PPoints;
    private javax.swing.JLabel PSR;
    private javax.swing.JLabel PTIME_TO_EXECUTE;
    private javax.swing.JLabel PTIME_TO_EXECUTE_AFTER;
    private javax.swing.JLabel PTime;
    // End of variables declaration//GEN-END:variables

}
